### ISSUE TITLE
Required Auth Methods which can scale beyond free quotas, for free? (read comment)

### ISSUE THREAD

**Issue by debosmit-git** [covid19india/eConsult#2]
Auth must be able to verify Phone Number.

**Comment by saquibkhan** [comment]
Few Questions:
Are we going to have a separate repo for backend and clients (web/mobile apps)? 
Is this report for the backend system? 
Any technology preferences?

**Comment by debosmit-git** [comment]
Google OAuth is flexible and suitable. Phone Number Verification will not be used as of now.
